import Foundation
import Testing
import OpenClawCore
import OpenClawGateway
import OpenClawProtocol
@testable import OpenClawAgents

/// Catalog-driven parity of the in-process gateway against an independent extraction of the
/// upstream method table and event list (`UpstreamGatewayMethodFixtures`, generated by
/// `Scripts/sync-upstream-gateway-method-fixtures.mjs`).
@Suite("Gateway method table parity")
struct GatewayMethodParityTests {
    private typealias Harness = GatewayServerTestHarness

    @Test
    func generatedCatalogMatchesTheUpstreamTable() {
        #expect(UpstreamGatewayMethodFixtures.upstreamCommit == GatewayMethodCatalog.upstreamCommitFull)
        #expect(GatewayMethodCatalog.descriptors.map(\.name) == UpstreamGatewayMethodFixtures.methods.map(\.name))
        for spec in UpstreamGatewayMethodFixtures.methods {
            guard let descriptor = GatewayMethodCatalog.byName[spec.name] else {
                Issue.record("\(spec.name) is missing from GatewayMethodCatalog")
                continue
            }
            #expect(descriptor.family == spec.family, "\(spec.name) family")
            #expect(descriptor.scope == spec.scope, "\(spec.name) scope")
            #expect(descriptor.since == spec.since, "\(spec.name) since")
            #expect(descriptor.advertised == spec.advertised, "\(spec.name) advertised")
            #expect(descriptor.startupGated == spec.startupGated, "\(spec.name) startupGated")
            #expect(descriptor.controlPlaneWrite == spec.controlPlaneWrite, "\(spec.name) controlPlaneWrite")
        }
        let upstreamNames = Set(UpstreamGatewayMethodFixtures.methods.map(\.name))
        #expect(GatewayMethodCatalog.removedSincePreviousPin.isDisjoint(with: upstreamNames))
    }

    @Test
    func eventVocabularyCoversUpstreamEvents() {
        let sdk = Set(GatewayEventName.allCases.map(\.rawValue))
        let missing = UpstreamGatewayMethodFixtures.events.filter { !sdk.contains($0) }
        #expect(missing.isEmpty, "GatewayEventName lacks \(missing)")
        #expect(GatewayEventFilter.sessionScopedEvents.isSubset(of: Set(UpstreamGatewayMethodFixtures.events)))
    }

    @Test
    func everyUpstreamMethodIsHandledOrAKnownStubOnTheRuntimeStack() async throws {
        let stack = await Harness.runtimeStack("parity-table", turns: [])
        let handled = Set(await stack.server.supportedMethods())
        var stubs: [String] = []
        for spec in UpstreamGatewayMethodFixtures.methods where !handled.contains(spec.name) {
            let response = await Harness.call(stack.server, spec.name)
            let code = response.error?.errorCode
            if spec.scope == "node" {
                #expect(code == .invalidRequest, "\(spec.name) (node) answered \(String(describing: code))")
            } else {
                // Known but not implemented in-process: UNAVAILABLE for valid params, INVALID_REQUEST otherwise.
                #expect(code == .unavailable || code == .invalidRequest, "\(spec.name) answered \(String(describing: code))")
                stubs.append(spec.name)
            }
        }
        #expect(!stubs.isEmpty)
        for removed in GatewayMethodCatalog.removedSincePreviousPin {
            let response = await Harness.call(stack.server, removed)
            #expect(response.error?.errorCode == .invalidRequest)
            #expect(response.error?.message.contains("removed upstream") == true)
        }
    }

    @Test
    func runtimeRegistrationsAreUpstreamMethodsWithCatalogScopes() async throws {
        let upstream = Dictionary(uniqueKeysWithValues: UpstreamGatewayMethodFixtures.methods.map { ($0.name, $0) })
        let registered = EmbeddedAgentRuntime.gatewayMethodNames
            + EmbeddedAgentRuntime.toolGatewayMethodNames
            + EmbeddedAgentRuntime.sessionBranchGatewayMethodNames
        let stack = await Harness.runtimeStack("parity-registrations", turns: [])
        let handled = Set(await stack.server.supportedMethods())
        for method in registered {
            #expect(upstream[method] != nil, "\(method) is not an upstream core method")
            #expect(handled.contains(method), "\(method) is not registered by attach(to:)")
            #expect(await stack.server.methodDescriptor(for: method)?.scope == upstream[method]?.scope, "\(method) scope")
        }
        let builtins = ["sessions.subscribe", "sessions.messages.subscribe", "sessions.messages.unsubscribe", "sessions.groups.list",
                        "sessions.groups.put", "sessions.groups.rename", "sessions.groups.update", "sessions.groups.delete",
                        "sessions.groups.defaults", "system-presence", "node.list", "node.pair.list", "node.pair.approve",
                        "node.pair.reject", "node.pair.remove", "node.rename"]
        for method in builtins {
            #expect(upstream[method] != nil, "\(method) is not an upstream core method")
            #expect(handled.contains(method), "\(method) has no built-in handler")
        }
        // Startup-gated runtime methods follow the upstream table.
        await stack.server.beginStartup()
        for method in registered + builtins where upstream[method]?.startupGated == true {
            let response = await Harness.call(stack.server, method)
            #expect(response.error?.isStartupUnavailable == true, "\(method) should be startup-gated")
        }
        await stack.server.completeStartup()
    }
}
